# Generated by Django 2.1 on 2021-12-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='full_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='purchases',
            old_name='full_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preview_image',
        ),
    ]
