# Generated by Django 2.1 on 2021-12-01 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_customorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='description_update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customorder',
            name='image_update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customorder',
            name='phase_0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customorder',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
